In [1]:
import pandas as pd 
import numpy as np
df = pd.read_csv("sample_data.csv")
df.head()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience,Joining_Date,Performance_Rating
0,101,Div,22,Male,IT,Delhi,55000,1,2024-01-15,4
1,102,Aman,24,Male,HR,Mumbai,48000,3,2022-06-10,3
2,103,Priya,23,Female,Finance,Pune,62000,2,2023-03-12,5
3,104,Rahul,26,Male,IT,Bangalore,75000,5,2020-09-25,4
4,105,Sneha,25,Female,Marketing,Jaipur,53000,4,2021-11-18,3

##### 6.Selecting data

In [3]:
df["Name"]

0        Div
1       Aman
2      Priya
3      Rahul
4      Sneha
5      Karan
6       Neha
7      Arjun
8     Simran
9      Vikas
10    Ritika
11    Manish
12     Pooja
13    Aditya
14     Kavya
15     Rohan
16    Anjali
17      Yash
18     Meera
19    Sachin
Name: Name, dtype: object

In [5]:
df[["Name","Salary"]]

      Name  Salary
0      Div   55000
1     Aman   48000
2    Priya   62000
3    Rahul   75000
4    Sneha   53000
5    Karan   81000
6     Neha   45000
7    Arjun   92000
8   Simran   57000
9    Vikas   88000
10  Ritika   61000
11  Manish   52000
12   Pooja   49000
13  Aditya   85000
14   Kavya   73000
15   Rohan   54000
16  Anjali   50000
17    Yash   95000
18   Meera   79000
19  Sachin   60000

In [9]:
# Selecting Rows using iloc

df.iloc[0]

Employee_ID                  101
Name                         Div
Age                           22
Gender                      Male
Department                    IT
City                       Delhi
Salary                     55000
Experience                     1
Joining_Date          2024-01-15
Performance_Rating             4
Name: 0, dtype: object

In [11]:
# it is used when selecting rows by position ,indexing
df.iloc[:5]

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience,Joining_Date,Performance_Rating
0,101,Div,22,Male,IT,Delhi,55000,1,2024-01-15,4
1,102,Aman,24,Male,HR,Mumbai,48000,3,2022-06-10,3
2,103,Priya,23,Female,Finance,Pune,62000,2,2023-03-12,5
3,104,Rahul,26,Male,IT,Bangalore,75000,5,2020-09-25,4
4,105,Sneha,25,Female,Marketing,Jaipur,53000,4,2021-11-18,3

In [15]:
# is used when u have to filter with labels like specific columns
df.loc[df["Age"] > 22]

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience,Joining_Date,Performance_Rating
1,102,Aman,24,Male,HR,Mumbai,48000,3,2022-06-10,3
2,103,Priya,23,Female,Finance,Pune,62000,2,2023-03-12,5
3,104,Rahul,26,Male,IT,Bangalore,75000,5,2020-09-25,4
4,105,Sneha,25,Female,Marketing,Jaipur,53000,4,2021-11-18,3
5,106,Karan,27,Male,Finance,Delhi,81000,6,2019-07-01,5
7,108,Arjun,28,Male,IT,Hyderabad,92000,7,2018-04-14,5
8,109,Simran,24,Female,Marketing,Mumbai,57000,3,2022-01-05,4
9,110,Vikas,29,Male,Finance,Bangalore,88000,8,2017-08-30,5
10,111,Ritika,23,Female,IT,Delhi,61000,2,2023-05-22,4
11,112,Manish,30,Male,HR,Jaipur,52000,9,2016-12-11,3
13,114,Aditya,27,Male,IT,Mumbai,85000,6,2019-10-09,5
14,115,Kavya,26,Female,Finance,Hyderabad,73000,5,2020-06-15,4
15,116,Rohan,25,Male,Marketing,Delhi,54000,4,2021-09-19,3
16,117,Anjali,24,Female,HR,Bangalore,50000,3,2022-02-25,4
17,118,Yash,29,Male,IT,Pune,95000,8,2017-05-08,5
18,119,Meera,28,Female,Finance,Mumbai,79000,7,2018-11-30,5
19,120,Sachin,31,Male,Marketing,Hyderabad,60000,10,2015-01-20,3

In [21]:
df.loc[1, "Name"]

'Aman'

In [25]:
df.iloc[1, 1]

'Aman'

In [29]:
# above both cells return "Aman"
# But :loc → by label/name
#iloc → by number position

##### 7. Filtering Data