In [5]:
import pandas as pd 
import numpy as np
df = pd.read_csv("sample_data.csv")
df.head()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience,Joining_Date,Performance_Rating
0,101,Div,22,Male,IT,Delhi,55000,1,2024-01-15,4
1,102,Aman,24,Male,HR,Mumbai,48000,3,2022-06-10,3
2,103,Priya,23,Female,Finance,Pune,62000,2,2023-03-12,5
3,104,Rahul,26,Male,IT,Bangalore,75000,5,2020-09-25,4
4,105,Sneha,25,Female,Marketing,Jaipur,53000,4,2021-11-18,3

##### 6.Selecting data

In [8]:
df["Name"]

0        Div
1       Aman
2      Priya
3      Rahul
4      Sneha
5      Karan
6       Neha
7      Arjun
8     Simran
9      Vikas
10    Ritika
11    Manish
12     Pooja
13    Aditya
14     Kavya
15     Rohan
16    Anjali
17      Yash
18     Meera
19    Sachin
Name: Name, dtype: object

In [10]:
df[["Name","Age"]]

      Name  Age
0      Div   22
1     Aman   24
2    Priya   23
3    Rahul   26
4    Sneha   25
5    Karan   27
6     Neha   21
7    Arjun   28
8   Simran   24
9    Vikas   29
10  Ritika   23
11  Manish   30
12   Pooja   22
13  Aditya   27
14   Kavya   26
15   Rohan   25
16  Anjali   24
17    Yash   29
18   Meera   28
19  Sachin   31