#### Introduction to Pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
print("pandas version :",pd.__version__)

pandas version : 2.2.2

#### Creating Series

In [5]:
# Creating Pandas Series

data = [10, 20, 30, 40]

series = pd.Series(data)

print(series)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
# Custom Index

series = pd.Series(data, index=['a', 'b', 'c', 'd'])

print(series)

a    10
b    20
c    30
d    40
dtype: int64

#### Creating DataFrames

In [8]:
# Creating DataFrame from Dictionary

data = {
    "Name": ["Div", "Aman", "Rahul", "Priya"],
    "Age": [22, 23, 21, 24],
    "City": ["Delhi", "Mumbai", "Jaipur", "Pune"]
}

df = pd.DataFrame(data)

df

    Name  Age    City
0    Div   22   Delhi
1   Aman   23  Mumbai
2  Rahul   21  Jaipur
3  Priya   24    Pune

In [9]:
# DataFrame from List

data = [
    [1, "Laptop", 50000],
    [2, "Phone", 30000],
    [3, "Tablet", 20000]
]

df = pd.DataFrame(data, columns=["ID", "Product", "Price"])

df

   ID Product  Price
0   1  Laptop  50000
1   2   Phone  30000
2   3  Tablet  20000

#### Reading Data

In [11]:
# Reading CSV File

df = pd.read_csv("sample_data.csv") # for excel file use .xlsx

df.head()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience,Joining_Date,Performance_Rating
0,101,Div,22,Male,IT,Delhi,55000,1,2024-01-15,4
1,102,Aman,24,Male,HR,Mumbai,48000,3,2022-06-10,3
2,103,Priya,23,Female,Finance,Pune,62000,2,2023-03-12,5
3,104,Rahul,26,Male,IT,Bangalore,75000,5,2020-09-25,4
4,105,Sneha,25,Female,Marketing,Jaipur,53000,4,2021-11-18,3

#### Understanding Data

In [13]:
df.info() # basic info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         20 non-null     int64
 1   Name                20 non-null     object
 2   Age                 20 non-null     int64
 3   Gender              20 non-null     object
 4   Department          20 non-null     object
 5   City                20 non-null     object
 6   Salary              20 non-null     int64
 7   Experience          20 non-null     int64
 8   Joining_Date        20 non-null     object
 9   Performance_Rating  20 non-null     int64
dtypes: int64(5), object(5)
memory usage: 1.7+ KB

In [14]:
df.describe() # Statstical info

       Employee_ID        Age        Salary  Experience  Performance_Rating
count     20.00000  20.000000     20.000000   20.000000           20.000000
mean     110.50000  25.700000  65700.000000    4.750000            4.100000
std        5.91608   2.867238  16193.240955    2.788605            0.788069
min      101.00000  21.000000  45000.000000    1.000000            3.000000
25%      105.75000  23.750000  52750.000000    2.750000            3.750000
50%      110.50000  25.500000  60500.000000    4.500000            4.000000
75%      115.25000  28.000000  79500.000000    7.000000            5.000000
max      120.00000  31.000000  95000.000000   10.000000            5.000000

In [15]:
# Column Names

df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'Salary',
       'Experience', 'Joining_Date', 'Performance_Rating'],
      dtype='object')

In [16]:
# Shape of Dataset

df.shape

(20, 10)

In [17]:
# Data Types

df.dtypes

Employee_ID            int64
Name                  object
Age                    int64
Gender                object
Department            object
City                  object
Salary                 int64
Experience             int64
Joining_Date          object
Performance_Rating     int64
dtype: object

#### Selecting data

In [19]:
# Selecting Single Column

df["Name"]

0        Div
1       Aman
2      Priya
3      Rahul
4      Sneha
5      Karan
6       Neha
7      Arjun
8     Simran
9      Vikas
10    Ritika
11    Manish
12     Pooja
13    Aditya
14     Kavya
15     Rohan
16    Anjali
17      Yash
18     Meera
19    Sachin
Name: Name, dtype: object

In [20]:
# Multiple Columns

df[["Name", "Age"]]

      Name  Age
0      Div   22
1     Aman   24
2    Priya   23
3    Rahul   26
4    Sneha   25
5    Karan   27
6     Neha   21
7    Arjun   28
8   Simran   24
9    Vikas   29
10  Ritika   23
11  Manish   30
12   Pooja   22
13  Aditya   27
14   Kavya   26
15   Rohan   25
16  Anjali   24
17    Yash   29
18   Meera   28
19  Sachin   31

In [21]:
# Selecting Rows using iloc

df.iloc[0,0]

101

In [22]:
# Selecting Rows using loc

df.loc[0,"Name"]

'Div'

In [23]:
# Slicing

df.iloc[0:3]

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience,Joining_Date,Performance_Rating
0,101,Div,22,Male,IT,Delhi,55000,1,2024-01-15,4
1,102,Aman,24,Male,HR,Mumbai,48000,3,2022-06-10,3
2,103,Priya,23,Female,Finance,Pune,62000,2,2023-03-12,5